name: mlflow_env
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - numpy
  - pandas
  - pip:
      - mlflow==2.22.5
      - dagshub
      - scikit-learn
      - seaborn
      - matplotlib